### ISSUE TITLE
抓不到代理IP了

### ISSUE THREAD

**Issue by EmpRamses** [WiseDoge/ProxyPool#1]
我用的是你提供的Windows二进制文件dist，结果没有抓到IP，过了一段时间检测到代理池是空的就自动停止了

**Comment by liuslnlp** [comment]
是这样的，因为这些免费代理网站的网站HTML的结构更新了，所以导致爬虫模块的解析代码出现错误，你可以根据需要修改一下`proxyGetter.py`文件下`FreeProxyGetter`类中以crawl_开头的函数，使抓取模块正常工作。
