### ISSUE TITLE
请问，输入 最后一步proxypool_run之后,出现错误,由于计算机积极拒绝,无法连接,怎么解决呢？还有redis应该放在哪里？

### ISSUE THREAD

**Issue by xiao1i** [WiseDoge/ProxyPool#12]

**Comment by Raibows** [comment]
同样遇到这个问题。windows 平台下，启动redis server后并没有被连接，计算机积极拒绝。

**Comment by liuslnlp** [comment]
1. 请粘贴详细的报错信息。
2. Redis 放置到任何位置都可以，但需要配置环境变量。

**Comment by Raibows** [comment]
> 1. 请粘贴详细的报错信息。
> 2. Redis 放置到任何位置都可以，但需要配置环境变量。

放弃Windows了， Linux正常。感谢！
