### ISSUE TITLE
大佬 你这个取出四分之一IP检测 只是取了元素 所有的IP都还在集合里

### ISSUE THREAD

**Issue by liusanye** [WiseDoge/ProxyPool#6]
检测完了又塞回SET，你取出来的时候并没有删除取出来的元素 ，然后再塞回去？ 那你IP库会越来越多啊 并不会把不好的删了啊

**Comment by liuslnlp** [comment]
感谢！一会就改



在 2018年3月12日，20:27，liusanye <notifications@github.com<mailto:notifications@github.com>> 写道：


检测完了又塞回SET，你取出来的时候并没有删除取出来的元素 ，然后再塞回去？ 那你IP库会越来越多啊 并不会把不好的删了啊
